[project]
name = "movie-searching"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "nltk==3.9.1",
    "sentence-transformers>=5.1.2",
    "tqdm>=4.67.1",
]
